---
- name: testing connection
  hosts: dev_hosts
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
  vars_prompt:
    - name: ansible_user
      prompt: Enter the Cisco Username
      unsafe: yes
      private: yes
    - name: ansible_password
      prompt: Enter the Cisco password
      unsafe: yes
      private: yes
  
  tasks:
    - name: show cisco version
      ios_command:
        commands: show version
      register: result
    
    - name: show result
      debug:
        msg: "{{ result }}"
