---
- name: Cyberark example
  hosts: localhost
  vars:
    target_username: test_user1
    vault_location: test_vault1
  vars_prompt:
    - name: cyberark_url
      prompt: Enter the url
      private: no
      unsafe: yes
    - name: target_username
      prompt: Enter the username to retrieve
      unsafe: yes
      private: yes
  
  tasks:
    - name: credential retrieval advanced
      cyberark.pas.cyberark_credential:
        api_base_url: "{{ cyberark_url }}"
        client_cert: /etc/pki/ca-trust/source/client.pem
        client_key: /etc/pki/ca-trust/source/priv-key.pem
        #validate_certs: no
        app_id: 
        query: "safe=;folder=;object="
        connection_timeout: 60
        query_format: Exact
        reason: "requesting credential for Ansible deployment"
      register: cyberark_credential
      no_log: true

    - name: display user details
      debug:
        msg: "{{ cyberark_credential }}"
