---
- name: Cyberark example
  hosts: localhost
  vars:
    target_username: test_user1
    vault_location: test_vault1
  vars_prompt:
    - name: cyberark_url
      prompt: Enter the url
      private: no
      unsafe: yes
    - name: cyberark_username
      prompt: Enter the url Username
      unsafe: yes
      private: yes
    - name: cyberark_password
      prompt: Enter the url password
      unsafe: yes
      private: yes
    - name: target_username
      prompt: Enter the username to retrieve
      unsafe: yes
      private: yes
  
  tasks:
    - name: connect to CyberArk
      cyberark.pas.cyberark_authentication:
        api_base_url: "{{ cyberark_url }}"
        username: "{{ cyberark_username }}"
        password: "{{ cyberark_password }}"
        use_cyberark_authentication: yes
        use_ldap_authentication: no
        use_radius_authentication: no
        use_windows_authentication: no
        use_shared_logon_authentication: no

    - name: show the return values from connection
      debug:
        msg: "{{ cyberark_authentication }}"
  
    - name: credential retrieval advanced
      cyberark_credential:
        api_base_url: "{{ cyberark_url }}"
        validate_certs: no
        app_id: 
        query: "safe=;folder=;object="
        connection_timeout: 60
        query_format: Exact
        reason: "requesting credential for Ansible deployment"
      register: cyberark_credential
    
    - name: display user details
      debug:
        msg: "{{ cyberark_credential }}"
    
    - name: Logoff from CyberArk Vault
      cyberark_authentication:
        state: absent
        cyberark_session: '{{ cyberark_session }}'