---
# example for date math functions.
- name: test date func
  hosts: localhost
  vars: 
    - file_date: "20210820"
    - vms: "100-107"

  tasks:
    - name: get current date
      local_action: command date +%Y%m%d
      run_once: true
      register: date
  
    - name: show date
      debug:
       msg: "{{ ((date.stdout | to_datetime('%Y%m%d')) - (file_date | to_datetime('%Y%m%d'))).days  }}"

    - name: loop range lol
      debug: 
        msg: "{{ item }}"
      with_sequence: start="{{ vms.split('-')[0]| int }}" end="{{ vms.split('-')[1]| int }}"
      
