---
# example for date math functions.
- name: test date func
  hosts: "{{ hosts }}"
  vars: 
    - file_date: "20210820"

  tasks:
    - name: get current date
      local_action: command date +%Y%m%d
      run_once: true
      register: date
      delegate_to: localhost
  
    - name: show number of days elapsed since file_date
      debug:
       msg: "{{ ((date.stdout | to_datetime('%Y%m%d')) - (file_date | to_datetime('%Y%m%d'))).days  }}"
    
    - name: show default
      debug:
       msg: "{{ lol | default('') }}"
