---
- name: test date func
  hosts: localhost
  vars: 
    - file_date: "20210820"
  tasks:
    - name: get current date
      local_action: command date +%Y%m%d
      run_once: true
      register: date
  
    - name: show today
      debug:
       msg: "{{ (('20160814' | to_datetime('%Y%m%d')) - ('20151225' | to_datetime('%Y%m%d'))).days  }}"
       #"{{ date.stdout |to_datetime('%Y%m%d') }}"
       
    - name: show date
      debug:
       #msg: "{{ (date.stdout | to_datetime('%Y%m%d')).days }}"
       msg: "{{ ((date.stdout | to_datetime('%Y%m%d')) - (file_date | to_datetime('%Y%m%d'))).days  }}"