- name: find and rename vms by folder
  hosts: localhost
  gather_facts: no
  vars: 
    - folder: "Decommission_VMs"
    - vms_to_rename: []
    - datacenter_name: "Datacenter01"
  roles:
    - rename_old_vms
