---
- name: file lookup plugin example
  hosts: localhost
  vars:
    my_dir: ./
  tasks:
    - name: set a var
      ansible.builtin.set_fact:
        file_content: "{{ lookup('ansible.builtin.file', my_dir + 'README.md') }}"

    - name: show file
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ file_content.split('\n') }}"

