---
- name: Run a series of Commands
  hosts: your_host_group
  connection: local
  vars_prompt:
    - name: device_user
      prompt: Enter the username
      unsafe: yes
      private: yes
    - name: device_password
      prompt: Enter the password
      unsafe: yes
      private: yes
    - name: bank_number
      prompt: Enter which bank (A/B)
      unsafe: yes
      private: yes
    - name: firmware_filename
      prompt: Enter the firmware filename
      unsafe: yes
      private: yes

  tasks:
    - name: generate first conf file
      ansible.builtin.template:
        src: process_one.j2
        dest: process_one.json

    - name: process 1
      command: your_command.py process_one.json
      register: process_1_result

    - name: show process 1 result
      debug:
        msg: "{{ process_1_result }}"
    
    - name: generate second conf file
      ansible.builtin.template:
        src: process_two.j2
        dest: process_two.json

    # run command up to 10 times every 15 secs until result contains "Idle"
    - name: process 2
      command: your_command.py process_two.json
      register: process_2_result
      until: process_2_result.stdout.find("Idle") == 1
      retries: 10
      delay: 15

    - name: show process 2 result
      debug:
        msg: "{{ process_2_result }}"
    
    - name: generate third conf file
      ansible.builtin.template:
        src: process_three.j2
        dest: process_three.json

    - name: process 3
      command: your_command.py process_three.json
      register: process_3_result

    - name: show process 3 result
      debug:
        msg: "{{ process_3_result }}"