---
- name: test loop
  hosts: localhost
  vars:
    - profiles:
      - profile_name: "first_profile"
        nodes:
          - "node1"
          - "node2"
      - profile_name: "second_profile"
        nodes:
          - "node3"
          - "node4"
    - vms: "100-107"
    - ips: "8.8.8.8,9.9.9.9"
    - ip: "8.8.8.8"
    - generic_list: ["one", "two"]


  tasks:
    - name: loop range lol
      debug:
        msg: "{{ item }}"
      with_sequence: start="{{ vms.split('-')[0]| int }}" end="{{ vms.split('-')[1]| int }}"

    - name: show list of comma sep strings
      debug:
        msg:
          - "{{ ips.split(',') }}"
          - "{{ ip.split(',') }}"
    - name: loop
      debug:
        msg: "{{ item }}"
      loop: "{{ ips.split(',') }}"

    - name: show it
      debug:
        msg: "{{ item.profile_name }} {{ item.nodes }}"
      loop: "{{ profiles }}"

    - name: ad hoc list of dictionaries
      debug:
        msg: "{{ item.config }}"
      with_items:
        - { config: lol }
        - { config: hay }

    - name: item in list
      ansible.builtin.debug:
        msg: "{{ item in generic_list }}"
      loop: 
        - "one"
        - "five"
