---
- name: simple regex example
  hosts: localhost
  vars:
    string1: |
      Network  next hop metric loc perf
      *>e8.8.4.0/24 8.8.8.8 0 0 11323 ?
      *>e9.9.9.1/22 8.8.8.8 0 0 12323 ?
      *>e7.7.7.2/22 8.8.8.8 0 0 12323 ?

  tasks:
    - name: initialize routed network list
      ansible.builtin.set_fact:
        routed_networks: []

    - name: collect networks from output
      ansible.builtin.set_fact:
        routed_networks: "{{ routed_networks + [item | regex_search('\\be(?:[0-9]{1,3}\\.){3}[0-9]{1,3}/([1-9][1-9])\\b')] }}"
      loop: "{{ string1.split('\n') }}"
      when: item | regex_search('\\be(?:[0-9]{1,3}\\.){3}[0-9]{1,3}/([1-9][1-9])\\b') is not none

    - name: show routed networks
      ansible.builtin.debug:
        msg: "{{ routed_networks }}"
...
