---
- name: test shell command with expect 
  hosts: all
  # store credentials in ansible-vault encrypted file
  vars_files:
    - password_file.yml
  tasks:
    - name: copy ftp files from remote host
      shell: |
        set verbose_flag 1
        spawn ftp
        send "open {{ ftp_host }}\n"
        expect Name*
        send "{{ ftp_user }}\n"
        expect Password*
        send "{{ ftp_pass }}\n"
        expect "ftp*"
        send "get FILENAME\n"
        expect "ftp*"
        send "bye\n"
      args:
        executable: /usr/bin/expect
      register: ftp_output
    
    - name: show output
      debug:
        msg: "{{ ftp_output }}"
