---
- name: Simulate a long running playbook/task
  hosts: all
  gather_facts: false
  tasks:
    - name: Run the wait for module for specified time period
      ansible.builtin.wait_for:
        timeout: "{{ timeout_seconds }}"
      delegate_to: locahost
...