---
# run this playbook to export the db keys from an existing AAP instance
# ansible-playbook -i inventory_cluster retrieve_secrets.yml
# 
# when you run the installer add the exported secrets file to the extra vars of the bundle installer
# ansible-playbook -i inventory_cluster ansible.containerized_installer.install -e @../passwords.yml -e @../exported_secrets.yml
#
# when you restore the previous backup the keys will match what was in the DB beforeA
#
- name: Retrieve secrets from AAP
  hosts: all
  gather_facts: false
  become: false
  tasks:

    - name: Grab secrets
      containers.podman.podman_secret_info:
        showsecret: true
      register: pod_secret_info

    - name: Set a new fact
      ansible.builtin.set_fact:
        exported_secrets: |
          {{
            raw_data |
            json_query(raw_data_query)
          }}
      vars:
        raw_data: >-
          {{
            pod_secret_info['secrets'] |
            selectattr('Spec.Name', 'contains', 'secret')
          }}
        raw_data_query: '[].{key_name: Spec.Name, secret: SecretData}'

    - name: Convert export to a usable variable format
      ansible.builtin.set_fact:
        generated_variables: >-
          {{
            generated_variables | default({}) |
            combine(hostvars[item]['exported_secrets'] | default([]) |
            items2dict(key_name='key_name', value_name='secret') 
            )
          }}
      loop: "{{ ansible_play_hosts }}"
      run_once: true

    - name: Convert my data to a yaml file
      ansible.builtin.copy:
        content: |
          ---

          {{
            generated_variables | to_nice_yaml
          }}
          ...

        dest: >-
          {{
            playbook_dir +
            '/exported_cluster_secrets_' + 
            lookup('pipe', 'date +%Y%m%d_%H%M%S') +
            '.yml'
          }}

        mode: '0600'
      delegate_to: localhost
      run_once: true
...
